version: '3'

services:
  detection_app:
    build: 
      context: .
    networks:
      - my_network
    ports:
      - "8080:8080"

  streamlit_app:
    build:
      context: .
    networks:
      - my_network
    ports:
      - "8501:8501"
networks:
  my_network:
    driver: bridge